language: go

go:
  - 1.14.2

script:
  - make build-wasm

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: wasm
  on:
    branch: master
